import React from 'react';
import { Badge } from './ui.jsx';

export default function Connections({ saved, canPersist, storageMessage }) {
  return <><section className="panel"><header className="panel-head"><div><p className="eyebrow">Connection register</p><h2>Know the source of each state.</h2></div><Badge kind="info">PREVIEW</Badge></header>
    <div className="connection-row"><div className="connection-symbol mono">01</div><div><h3>Browser treasury simulation</h3><p>Runs the fixed treasury rules on synthetic USDC. Your own simulation is saved only in this browser.</p><details><summary>Storage and authority</summary><p>The preview uses its own record. Existing treasury and advisory records are untouched. The simulation can neither sign nor submit transactions.</p><p>{canPersist ? 'Safe browser persistence is available in this environment.' : storageMessage || 'Web Locks or secure browser APIs are unavailable. Sample inspection remains available.'}</p></details></div><Badge kind={canPersist ? 'ok' : 'warn'}>{saved ? 'LOCAL RECORD' : canPersist ? 'AVAILABLE' : 'READ ONLY'}</Badge></div>
    <div className="connection-row"><div className="connection-symbol mono">02</div><div><h3>Persistent knowledge mesh</h3><p>The product service retains source revisions and analyses. This Control Centre currently shows embedded synthetic examples.</p><details><summary>What a connection would provide</summary><ul><li>Authenticated access to an owner’s source records.</li><li>Current graph snapshots and retained analysis history.</li><li>Source capture status and failure details.</li></ul><p>This preview makes no service requests and does not collect access tokens.</p><a className="btn" href="/mesh/" style={{ marginTop: 16 }}>Open knowledge mesh ↗</a></details></div><Badge>DISCONNECTED</Badge></div>
    <div className="connection-row"><div className="connection-symbol mono">03</div><div><h3>Kamino deployment documentation</h3><p>A registered source connector for the official program deployment README.</p><details><summary>Inspect the connector boundary</summary><p>Document evidence can establish a stated deployment reference. It does not establish lending liquidity or authorize a transaction.</p><a className="btn" href="https://github.com/Kamino-Finance/klend/blob/master/README.md" target="_blank" rel="noopener noreferrer" style={{ marginTop: 16 }}>Official source ↗</a></details></div><Badge>NOT CAPTURED</Badge></div>
    <div className="connection-row"><div className="connection-symbol mono">04</div><div><h3>Solana Devnet program account</h3><p>A registered source connector checks the Devnet network identity and the Kamino program account.</p><details><summary>Inspect the connector boundary</summary><p>Account and document evidence can support an OBSERVED result. Lending usability and wallet ownership are not assessed.</p><dl className="facts"><div><dt>Network</dt><dd>Solana Devnet</dd></div><div><dt>Program</dt><dd>KLend2g3cP87fffoy8q1mQqGKjrxjC8boSyAYavgmjD</dd></div></dl></details></div><Badge>NOT CAPTURED</Badge></div>
    <div className="connection-row"><div className="connection-symbol mono">05</div><div><h3>Wallet and execution terminal</h3><p>The repository has a separate wallet-owned Devnet terminal. This preview has no wallet or signing authority.</p><details><summary>Execution status</summary><p>Existing swap research does not prove treasury lending supply or redemption. No lending execution has been verified by this prototype.</p><a className="btn" href="/mesh/#lending-title" style={{ marginTop: 16 }}>Open Devnet lending terminal ↗</a></details></div><Badge>NOT CONNECTED</Badge></div></section>
    <div className="connections-map"><div><p className="eyebrow">Local</p><h3>Treasury record</h3><p>Synthetic commands and outcomes stay in a separate browser record.</p></div><div><p className="eyebrow">Service</p><h3>Knowledge records</h3><p>The product stores source revisions and analyses in its mesh service.</p></div><div><p className="eyebrow">Wallet</p><h3>Devnet records</h3><p>The existing terminal keeps wallet-scoped records. They are not merged here.</p></div></div></>;
}
