import React, { useState } from 'react';
import { BALANCES, Badge, Facts, eventName, evidenceAge, fieldError, money, statusKind, when } from './ui.jsx';

function nodeValue(node) {
  const data = node.data;
  if (node.id === 'mandate') return `${money(data.investmentCapUnits)} USDC`;
  if (node.id === 'observation') return data.observation?.availableLiquidityUnits ? `${money(data.observation.availableLiquidityUnits)} USDC` : 'No data';
  return `${money(data[node.id === 'reserve' ? 'reserveUnits' : node.id === 'undelegated' ? 'undelegatedUnits' : node.id === 'account' ? 'idleUnits' : 'positionUnits'])} USDC`;
}
function GraphNode({ node, selected, evidence, choose }) {
  const value = nodeValue(node), included = evidence.includes(node.id);
  return <button className={`trace-node ${selected === node.id ? 'selected' : ''} ${included ? 'evidence' : ''}`} data-node={node.id} data-evidence={included} aria-pressed={selected === node.id} onClick={() => choose(node.id)}><span className="node-type">{node.kind.replaceAll('-', ' ')}</span><span className="node-label">{node.label}</span><span className="node-value" style={value.length > 18 ? { fontSize: 13 } : undefined}>{value}</span>{included && <span className="sr-only">Selected rule evidence</span>}</button>;
}
function ObservationForm({ locked, observe }) {
  const [values, setValues] = useState({ liquidity: '600', age: '0' });
  const [errors, setErrors] = useState({});
  function submit(event) {
    event.preventDefault();
    const next = Object.fromEntries(Object.entries(values).map(([key, value]) => [key, fieldError(key, value)]));
    setErrors(next);
    if (Object.values(next).some(Boolean)) { event.currentTarget.querySelector(`[name="${Object.keys(next).find(key => next[key])}"]`)?.focus(); return; }
    observe(values.liquidity.trim(), Number(values.age));
  }
  return <form id="evidence-form" className="observation-form" noValidate onSubmit={submit}>{[['liquidity', 'Available liquidity, USDC'], ['age', 'Evidence age, seconds']].map(([name, label]) => <label className="field" key={name}><span>{label}</span><input name={name} value={values[name]} onChange={event => setValues({ ...values, [name]: event.target.value })} onBlur={() => setErrors({ ...errors, [name]: fieldError(name, values[name]) })} {...(name === 'liquidity' ? { inputMode: 'decimal', maxLength: 21 } : { type: 'number', min: 0, max: 86400, step: 1 })} required disabled={locked} aria-invalid={Boolean(errors[name])} aria-describedby={`custom-${name}-error`} /><span className="field-error" id={`custom-${name}-error`}>{errors[name]}</span></label>)}<button type="submit" className="btn" data-mutate disabled={locked}>Record observation</button></form>;
}

export default function Decisions({ run, view, own, at, trace, selectedNode, selectedCheck, selectedEvent, historyPage, setHistoryPage, selectNode, selectCheck, selectEvent, currentGraph, locked, loop, toggleLoop, command, preset, observe, revoke, exportRun }) {
  const { graph, decision, entry } = trace;
  const nodes = Object.fromEntries(graph.nodes.map(node => [node.id, node]));
  const selected = nodes[selectedNode] || nodes.observation;
  const check = decision?.checks.find(item => item.id === selectedCheck);
  const evidence = check?.evidenceNodeIds || [];
  const before = { reserveUnits: nodes.reserve.data.reserveUnits, undelegatedUnits: nodes.undelegated.data.undelegatedUnits, idleUnits: nodes.account.data.idleUnits, positionUnits: nodes.position.data.positionUnits };
  const after = entry?.balances || before;
  const node = id => <GraphNode node={nodes[id]} selected={selectedNode} evidence={evidence} choose={selectNode} />;
  return <><section className="command-bar"><div className="od-field"><span className={`small mono ${loop.running ? 'green' : 'muted'}`} id="loop-state">{loop.running ? `Running · ${10 - loop.remaining}/10 saved · Next cycle in 5s` : 'Stopped · Starts only when you choose'}</span><p>{own ? 'Cycles use the last saved synthetic observation.' : 'Explore a saved example. Create your own simulation to run cycles.'}</p></div><div className="actions"><button className="btn" id="start-loop" data-action="toggle-loop" disabled={!loop.running && (locked || view.state.revoked)} onClick={toggleLoop}>{loop.running ? 'Stop loop' : 'Start 10 cycles'}</button><button className="btn primary" data-action="cycle" data-mutate data-agent="true" disabled={locked || view.state.revoked} onClick={() => command('cycle')}>Run one cycle <span aria-hidden="true">→</span></button></div></section>
    <div className="workspace-grid"><div className="od-stack" style={{ '--od-gap': '24px', display: 'flex' }}><section className="panel"><header className="panel-head"><div><p className="eyebrow">{entry ? `Saved input / event ${String(view.entries.indexOf(entry) + 1).padStart(2, '0')}` : 'Current input / next cycle'}</p><h2>{entry ? 'The graph behind this event.' : 'Trace the next decision.'}</h2></div>{entry ? <button className="btn subtle" data-action="current-graph" onClick={currentGraph}>Current input</button> : <Badge kind="info">PREVIEW</Badge>}</header><div className="panel-body"><div className="trace-summary"><div className="od-row"><span className={`number ${decision?.status === 'READY' ? 'green' : 'amber'}`}>{decision?.action || 'RECORD'}</span><Badge kind={statusKind(decision?.status)}>{decision?.status || 'RECORDED'}</Badge></div><span className="small mono muted">{when(graph.at)} UTC</span></div><p className="detail-copy" style={{ margin: 0 }}>{decision?.reasons[0] || entry?.outcome.message || 'No decision recorded.'}</p></div><div className="graph-board"><div className="trace-chain">{node('mandate')}<span className="edge-note" aria-label="authorizes">→</span>{node('account')}</div><div className="graph-relation">mandate authorizes account · account owns position ↓</div><div className="trace-chain">{node('position')}<span className="edge-note" aria-label="depends on">→</span>{node('observation')}</div><div className="graph-relation">position depends on observation</div><div className="excluded">{node('reserve')}{node('undelegated')}</div><p className="graph-relation" style={{ paddingTop: 16 }}>Mandate excludes both cash balances above.</p></div><footer className="panel-foot"><p>{entry ? 'Original input graph. Selecting it never changes the current run.' : 'A preview does not record an event or move a balance.'}</p></footer></section>
      <section className="panel"><header className="panel-head"><div><p className="eyebrow">Before → After</p><h2>{entry ? 'Recorded balance changes.' : 'No change until a cycle.'}</h2></div><span className="label">USDC</span></header><div className="panel-body">{BALANCES.map(([key, name]) => <div className="compare-row" key={key}><span>{name}</span><span className="number muted">{money(before[key])}</span><span className="muted">→</span><span className={`number ${before[key] !== after[key] ? 'green' : ''}`}>{money(after[key])}</span></div>)}<p className="detail-copy">{entry ? entry.outcome.message : 'The next action is evaluated again when you run a cycle.'}</p></div></section>
      <section className="panel" id="history-panel"><header className="panel-head"><div><p className="eyebrow">Record / {run.events.length} of 200 events</p><h2>Replay the ledger.</h2></div><button className="btn" data-action="export" onClick={exportRun}>Export JSON ↓</button></header><div className="history-list">{view.entries.length ? view.entries.slice(historyPage * 40, (historyPage + 1) * 40).map((item, offset) => <button className="history-item" key={item.eventId} data-history={item.eventId} aria-pressed={selectedEvent === item.eventId} onClick={() => selectEvent(item.eventId)}><span className="mono muted small">{String(historyPage * 40 + offset + 1).padStart(2, '0')}</span><span className="od-field"><span className="history-title">{eventName(item)}</span><span className="history-time">{when(item.at)} UTC · {money(item.outcome.amountUnits)} USDC moved</span></span><Badge kind={statusKind(item.decision?.status)}>{item.decision?.status || 'RECORDED'}</Badge></button>) : <div className="panel-body"><p className="muted">No saved events. Start by recording synthetic evidence.</p></div>}</div><footer className="panel-foot"><p>{own ? 'This browser record can be edited by its owner.' : 'Read-only sample run.'}</p>{view.entries.length > 40 && <div className="history-controls"><button className="btn" data-action="history-prev" disabled={historyPage === 0} onClick={() => setHistoryPage(historyPage - 1)}>Previous</button><span className="small mono">{historyPage + 1}/{Math.ceil(view.entries.length / 40)}</span><button className="btn" data-action="history-next" disabled={(historyPage + 1) * 40 >= view.entries.length} onClick={() => setHistoryPage(historyPage + 1)}>Next</button></div>}</footer></section></div>
      <div className="od-stack" style={{ '--od-gap': '24px' }}><section className="panel inspector-panel"><header className="panel-head"><div><p className="eyebrow">{check ? 'Selected rule' : 'Selected node'}</p><h2>{check?.label || selected.label}</h2></div></header><div className="panel-body">{check ? <><Badge kind={statusKind(check.status)}>{check.status}</Badge><p className="detail-copy">{check.detail}</p><p className="label" style={{ marginTop: 24 }}>Highlighted evidence</p><ul className="relation-list">{check.evidenceNodeIds.map(id => <li key={id}>{nodes[id].label}</li>)}</ul></> : <><p className="detail-copy" style={{ marginTop: 0 }}>{selected.detail}</p><Facts data={selected.data} /><details className="disclosure"><summary>Connected relationships</summary><ul className="relation-list">{graph.edges.filter(edge => edge.source === selected.id || edge.target === selected.id).map(edge => <li key={`${edge.source}:${edge.target}`}>{edge.source} → {edge.relation.replaceAll('_', ' ')} → {edge.target}</li>)}</ul></details></>}</div></section>
        <section className="panel"><header className="panel-head"><div><p className="eyebrow">Rule path</p><h2>{decision ? 'Every check explained.' : 'Observation event.'}</h2></div></header><div className="panel-body" style={{ paddingTop: 8, paddingBottom: 8 }}>{decision ? decision.checks.map(item => <button className="check-row" key={item.id} data-check={item.id} aria-pressed={selectedCheck === item.id} onClick={() => selectCheck(item.id)}><span>{item.label}</span><Badge kind={statusKind(item.status)}>{item.status}</Badge></button>) : <p className="detail-copy" style={{ margin: '16px 0' }}>This event updates evidence. It does not evaluate an action.</p>}</div></section>
        <section className="panel"><header className="panel-head"><div><p className="eyebrow">Synthetic input</p><h2>Change the conditions.</h2></div></header><div className="panel-body"><p className="form-note">{own ? 'Record an observation, then run a cycle.' : 'These controls become available in your own simulation.'}</p><p className="small mono muted" id="evidence-age" style={{ margin: '16px 0' }}>{own ? evidenceAge(view.state, at) : 'Sample time is fixed.'}</p><div className="preset-grid">{[['healthy', 'Healthy liquidity'], ['low', 'Low liquidity'], ['stale', 'Stale evidence'], ['unavailable', 'Unavailable']].map(([name, label]) => <button key={name} className="btn" data-action={`preset-${name}`} data-mutate disabled={locked} onClick={() => preset(name)}>{label}</button>)}</div><details className="disclosure"><summary>Custom synthetic observation</summary><ObservationForm locked={locked} observe={observe} /></details><details className="disclosure"><summary>Owner controls</summary><p className="detail-copy">Revocation stops agent movements. It does not withdraw the position. Owner redemption still depends on evidence and liquidity.</p><div className="actions" style={{ marginTop: 16 }}><button className="btn" id="owner-redeem" data-action="owner-redeem" data-mutate disabled={locked || BigInt(view.state.balances.positionUnits) === 0n} onClick={() => command('owner_redeem')}>Redeem position</button><button className="btn danger" data-action="revoke" data-mutate data-agent="true" disabled={locked || view.state.revoked} onClick={revoke}>Revoke mandate</button></div></details></div></section></div></div></>;
}
