import React, { useEffect, useRef, useState } from 'react';
import { Badge, Facts, money, statusKind, when } from './ui.jsx';

function Entity({ node, selected, source, choose }) {
  const amount = node.properties.amountUnits ?? node.properties.availableLiquidityUnits;
  return <button className={`entity-node ${selected === node.id && !source ? 'selected' : ''}`} data-entity={node.id} aria-pressed={selected === node.id && !source} onClick={() => choose(node.id)}><span className="label">{node.kind}</span><strong>{node.label}</strong>{amount && <span className="number">{money(amount)} <span className="small muted">USDC</span></span>}</button>;
}
function SourceButton({ source, choose, compact = false }) {
  return <button className="source-button" data-source={source.revisionId} onClick={() => choose(source.revisionId)}><span className={`mono ${compact ? 'green' : ''}`}>{source.sourceKey} <span className="green">↗</span></span><span className="small">{compact ? `${when(source.observedAt)} UTC · Synthetic source` : `Observed ${when(source.observedAt)} UTC · Captured ${when(source.capturedAt)} UTC`}</span></button>;
}
function Inspector({ pack, selected, sourceId, chooseSource }) {
  const source = pack.sources.find(item => item.revisionId === sourceId);
  if (source) return <><p className="eyebrow">Retained source / Sample</p><h2 style={{ marginTop: 8 }}>{source.sourceKey}</h2><Facts data={{ sourceUrl: source.sourceUrl, observedAt: source.observedAt, capturedAt: source.capturedAt, revisionId: source.revisionId, sha256: source.sha256 }} /><details className="disclosure"><summary>Read the exact source content</summary><pre className="source-json">{source.content}</pre></details><p className="detail-copy">This is a retained synthetic source, not a current live capture.</p></>;
  const node = pack.graph.nodes.find(item => item.id === selected);
  if (!node) return <p className="muted">Select an entity to inspect its evidence.</p>;
  const edges = pack.graph.edges.filter(edge => edge.source === node.id || edge.target === node.id);
  return <><p className="eyebrow">Selected entity / {node.kind}</p><h2 style={{ marginTop: 8 }}>{node.label}</h2><Facts data={{ 'Entity ID': node.id, ...node.properties }} /><details className="disclosure" open><summary>Connected relationships ({edges.length})</summary><ul className="relation-list">{edges.length ? edges.map(edge => <li key={edge.id}>{edge.source}<br /><span className="green">{edge.relation.replaceAll('_', ' ')} →</span><br />{edge.target}</li>) : <li>No relationship is present in this source snapshot.</li>}</ul></details><p className="label" style={{ marginTop: 24 }}>Supporting source revisions</p>{pack.sources.filter(item => node.sourceRevisionIds.includes(item.revisionId)).map(item => <SourceButton key={item.revisionId} source={item} choose={chooseSource} compact />)}</>;
}

export default function Knowledge({ data, state, setState, reduced, navigate, notify, exportSample }) {
  const { condition, depth, selected, source, query, pendingCondition, pendingDepth } = state;
  const [loading, setLoading] = useState(false);
  const timer = useRef(null);
  useEffect(() => () => clearTimeout(timer.current), []);
  const pack = data[condition], graph = pack.graph, analysis = pack.analyses[depth];
  const update = values => setState(previous => ({ ...previous, ...values }));
  const choose = id => update({ selected: id, source: null });
  const chooseSource = id => { update({ source: id }); document.getElementById('knowledge-inspector')?.scrollIntoView({ block: 'nearest', behavior: reduced ? 'instant' : 'smooth' }); };
  const node = id => <Entity node={graph.nodes.find(item => item.id === id)} selected={selected} source={source} choose={choose} />;
  function analyze() {
    if (loading) return;
    setLoading(true);
    timer.current = setTimeout(() => {
      update({ condition: pendingCondition, depth: pendingDepth, selected: 'observation:shared', source: null });
      setLoading(false); notify('Sample analysis opened. No live service was called.');
      document.getElementById('analyze-sample')?.focus({ preventScroll: true });
    }, reduced ? 0 : 240);
  }
  const directory = graph.nodes.filter(item => `${item.label} ${item.id} ${item.kind}`.toLowerCase().includes(query.toLowerCase()));
  return <><div className="banner"><p><span className="amber mono small">SAMPLE KNOWLEDGE</span><br />Explore a retained graph and its analysis. The mesh service is disconnected.</p><button className="btn" data-route-button="connections" onClick={() => navigate('connections')}>Connection status</button></div><div className="knowledge-toolbar"><label className="field"><span>Sample condition</span><select id="mesh-scenario" value={pendingCondition} onChange={event => update({ pendingCondition: event.target.value })}>{[['liquid', 'Liquid reserve'], ['illiquid', 'Low liquidity'], ['stale', 'Stale evidence'], ['missing', 'Missing relationship']].map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></label><label className="field"><span>Traversal depth</span><select id="mesh-depth" value={pendingDepth} onChange={event => update({ pendingDepth: event.target.value })}>{['3', '2', '1'].map(value => <option key={value} value={value}>{value} hop{value === '1' ? '' : 's'}</option>)}</select></label><button className="btn primary" data-action="analyze-sample" id="analyze-sample" disabled={loading} onClick={analyze}>Analyze sample →</button></div><div id="analysis-progress" role="status">{loading && <><div className="loading-line" aria-hidden="true" /><p className="sr-only">Tracing the retained sample.</p></>}</div>
    <div className="workspace-grid"><div className="od-stack" style={{ '--od-gap': '24px', display: 'flex' }}><section className="panel"><div className="knowledge-question"><p className="eyebrow">One question / Connected evidence</p><h2 style={{ marginTop: 8 }}>Can the connected positions exit?</h2></div><div className="mesh-lanes"><div className="mesh-lane">{node('observation:shared')}</div><span className="edge-note">{condition === 'missing' ? '×' : '→'}</span><div className="mesh-lane">{node('reserve:shared')}</div><span className="edge-note">←</span><div className="mesh-lane">{node('position:one')}{node('position:two')}</div></div><div className="panel-foot"><p>Observation observes reserve. Positions are supplied to that reserve.</p></div><div className="mesh-support">{node('protocol:demo')}{node('asset:usdc')}</div><div className="mesh-result"><div className="od-row" style={{ justifyContent: 'space-between' }}><h2>Analysis result</h2><Badge kind={statusKind(analysis.status)}>{analysis.status}</Badge></div><p>{analysis.summary}</p><div className="mini-facts" style={{ margin: '8px 0' }}><div className="od-stat"><span className="label">Connected positions</span><span className="number">{analysis.totalAffectedUnits === null ? 'N/A' : money(analysis.totalAffectedUnits)}</span><span className="small muted">Combined exit, USDC</span></div><div className="od-stat"><span className="label">Available liquidity</span><span className="number">{analysis.availableLiquidityUnits === null ? 'N/A' : money(analysis.availableLiquidityUnits)}</span><span className="small muted">Synthetic USDC</span></div></div><p className="small mono muted">{analysis.coverage.status.replaceAll('_', ' ')} · {new Set(analysis.coverage.visitedNodeIds).size} nodes visited · {depth} hop limit</p>{analysis.positionResults.length > 0 && <div className="ledger">{analysis.positionResults.map(position => <div className="ledger-row" key={position.positionId}><span className="small">{graph.nodes.find(item => item.id === position.positionId)?.label || position.positionId}</span><span className="ledger-value">{money(position.amountUnits)}</span><Badge kind={statusKind(position.status)}>{position.status}</Badge></div>)}</div>}<details className="disclosure"><summary>Inspect the analysis paths</summary>{analysis.positionResults.length ? analysis.positionResults.map(position => <p key={position.positionId} className="small mono muted" style={{ overflowWrap: 'anywhere', margin: '16px 0' }}>{position.pathNodeIds.join(' → ')}</p>) : <p className="detail-copy">No complete position path was returned. Inspect the coverage state and source relationships.</p>}<p className="detail-copy">The unrelated 700 USDC position uses another reserve. It is not included in this combined exit.</p></details></div></section>
      <section className="panel"><header className="panel-head"><div><p className="eyebrow">Sample source history</p><h2>Original evidence, retained.</h2></div><button className="btn" data-action="export-mesh" onClick={() => exportSample(condition, depth)}>Export sample ↓</button></header><div className="panel-body">{pack.sources.map(item => <SourceButton key={item.revisionId} source={item} choose={chooseSource} />)}<p className="detail-copy">Snapshot: {graph.asOf}. These source records are embedded examples. They are not saved by a connected service.</p></div></section></div>
      <div className="od-stack" style={{ '--od-gap': '24px' }}><section className="panel inspector-panel"><div className="panel-body" id="knowledge-inspector"><Inspector pack={pack} selected={selected} sourceId={source} chooseSource={chooseSource} /></div></section><section className="panel"><header className="panel-head"><div><p className="eyebrow">Graph directory</p><h2>Find an entity.</h2></div><span className="label">{graph.nodes.length} nodes</span></header><div className="panel-body"><label className="field"><span className="sr-only">Search graph entities</span><input id="entity-search" type="search" value={query} onChange={event => update({ query: event.target.value })} placeholder="Name, type, or ID" autoComplete="off" /></label><div id="entity-directory" className="directory-list">{directory.length ? directory.map(item => <Entity key={item.id} node={item} selected={selected} source={source} choose={choose} />) : <p className="muted">No matching entities. Try a name, type, or ID.</p>}</div><details className="disclosure"><summary>Every relationship ({graph.edges.length})</summary><ul className="relation-list">{graph.edges.map(edge => <li key={edge.id}>{edge.source}<br />{edge.relation.replaceAll('_', ' ')} → {edge.target}</li>)}</ul></details></div></section></div></div></>;
}
