import React, { useContext, useEffect, useRef } from 'react';
import { replayRun } from '../treasury/domain.mjs';
import { BALANCES, Badge, Figure, MotionPaused, capStyle, eventName, evidenceAge, evidenceState, money, ratio, statusKind, when } from './ui.jsx';

function BalanceChart({ run, view, chartEvent, selectChart }) {
  const paused = useContext(MotionPaused), chart = useRef(null);
  useEffect(() => {
    if (paused) return;
    const animation = chart.current?.animate?.([{ opacity: .5 }, { opacity: 1 }], { duration: 240, easing: 'ease-out' });
    return () => animation?.cancel();
  }, [run, chartEvent, paused]);
  const initial = replayRun({ ...run, events: [], ...(run.schemaVersion === 2 ? { records: [], legacyEventCount: 0 } : {}) }).state.balances;
  const all = [{ balances: initial, index: 0 }, ...view.entries.map((entry, index) => ({ ...entry, index: index + 1 }))];
  const points = all.slice(-31);
  const unitNumber = value => Number(BigInt(value)) / 1000000;
  const maximum = Math.max(unitNumber(view.state.mandate.investmentCapUnits), 1);
  const x = index => 58 + index / Math.max(points.length - 1, 1) * 676;
  const y = value => 224 - unitNumber(value) / maximum * 184;
  const path = key => points.map((point, index) => (index ? `H${x(index).toFixed(2)}V` : `M${x(0)} `) + y(point.balances[key]).toFixed(2)).join(' ');
  const active = chartEvent === null ? points.at(-1) : all.find(entry => entry.index === chartEvent) || points.at(-1);
  return <><div className="chart-meta"><div className="od-stat"><span className="label">Supplied position</span><span className="chart-value" style={capStyle(money(active.balances.positionUnits))}><Figure name="chart-position">{money(active.balances.positionUnits)}</Figure> <small>USDC</small></span><span className="small muted">{active.index === 0 ? 'Initial balance' : `After event ${String(active.index).padStart(2, '0')}`}</span></div><div className="legend"><span><i />Position</span><span><i className="idle" />Idle</span></div></div>
    <div className="chart-wrap"><svg className="balance-chart" ref={chart} viewBox="0 0 780 280" role="img" aria-labelledby="balance-chart-title balance-chart-desc"><title id="balance-chart-title">Delegated balance by recorded event</title><desc id="balance-chart-desc">{points.length} snapshots. Position and idle balances move between recorded events. The chart does not show market prices or returns. Exact balances are available in the event inspector.</desc>{[0, .5, 1].map(fraction => <React.Fragment key={fraction}><line className="gridline" x1="58" x2="734" y1={224 - fraction * 184} y2={224 - fraction * 184} /><text x="48" y={228 - fraction * 184} textAnchor="end">{(maximum * fraction).toLocaleString('en-US', { maximumFractionDigits: 2, notation: maximum > 100000 ? 'compact' : 'standard' })}</text></React.Fragment>)}{points.map((point, index) => <line key={point.index} className="gridline" x1={x(index)} x2={x(index)} y1="40" y2="224" opacity=".45" />)}<path d={`${path('positionUnits')} L${x(points.length - 1)} 224 L${x(0)} 224 Z`} fill="#9cdaa1" opacity=".06" /><path d={path('idleUnits')} className="idle-series" /><path d={path('positionUnits')} className="series" />{points.map((point, index) => <circle key={point.index} cx={x(index)} cy={y(point.balances.positionUnits)} r={point.index === active.index ? 4 : 2} fill="var(--green)" />)}<text x="58" y="253">{points[0].index === 0 ? 'START' : `EVENT ${points[0].index}`}</text><text x="734" y="253" textAnchor="end">EVENT {String(points.at(-1).index).padStart(2, '0')}</text></svg></div>
    <div className="chart-caption"><span>EVENTS, NOT MARKET TIME</span><span>{all.length > 31 ? 'LAST 30 EVENTS' : 'FIXED TOTAL'} / {money(view.state.balances.totalUnits)} USDC</span></div><div className="event-scrubber" aria-label="Inspect a balance snapshot">{points.filter(point => point.index === 0 || point.decision).map(point => <button key={point.index} className="event-step" data-chart={point.index} aria-pressed={point.index === active.index} aria-label={`Inspect ${point.index ? `event ${point.index}` : 'initial balance'}`} onClick={() => selectChart(point.index)}>{String(point.index).padStart(2, '0')}</button>)}</div></>;
}

export default function Overview({ run, view, own, at, loopRunning, chartEvent, selectChart, navigate, inspectLatest, openHistory, openEvent }) {
  const state = view.state, balances = state.balances;
  const last = view.entries.findLast(entry => entry.decision), decision = last?.decision;
  const observation = state.observation;
  const evidence = evidenceState(state, own ? at : state.at);
  const pass = decision?.checks.filter(check => check.status === 'PASS').length || 0;
  const evaluated = decision?.checks.filter(check => check.status !== 'SKIPPED').length || 0;
  const protectedAmount = (BigInt(balances.reserveUnits) + BigInt(balances.undelegatedUnits)).toString();
  return <><section className="total-strip" aria-label="Capital summary"><div className="od-stat"><span className="label">Total synthetic balance</span><span className="total-number number" style={capStyle(money(balances.totalUnits))}><Figure name="total">{money(balances.totalUnits)}</Figure><small>USDC</small></span><span className="stat-note">{own ? 'Browser-local simulation' : 'Sample ledger · No real funds'}</span></div><div className="od-stat"><span className="label">Outside agent authority</span><span className="stat-number" style={capStyle(money(protectedAmount))}>{money(protectedAmount)}</span><span className="stat-note">Reserve + undelegated cash</span></div><div className="od-stat"><span className="label">Agent budget</span><span className="stat-number green" style={capStyle(money(state.mandate.investmentCapUnits))}>{money(state.mandate.investmentCapUnits)}</span><span className="stat-note">Fixed investment cap · USDC</span></div><div className="od-stat"><span className="label">Mandate</span><span className={`stat-number ${state.revoked ? 'amber' : 'green'}`} style={{ fontSize: 24 }}>{state.revoked ? 'REVOKED' : 'ACTIVE'}</span><span className="stat-note">Agent {loopRunning ? 'loop running' : 'stopped'} · {run.events.length}/200 events</span></div></section>
    <div className="two-col"><section className="panel"><header className="panel-head"><div><p className="eyebrow">01 / Capital movement</p><h2>Every move, on record.</h2></div><Badge kind="info">USDC</Badge></header><BalanceChart run={run} view={view} chartEvent={chartEvent} selectChart={selectChart} /><footer className="panel-foot"><p>Discrete balances after each saved event.</p><button className="btn subtle" data-action="open-history" onClick={openHistory}>Open ledger ↗</button></footer></section>
      <section className="panel decision-card overview-decision"><header className="panel-head"><div><p className="eyebrow">02 / Latest decision</p><h2>{last ? 'Recorded outcome' : 'Awaiting a cycle'}</h2></div><Badge kind={statusKind(decision?.status)}>{decision?.status || 'NO DATA'}</Badge></header><div className="decision-main"><div className={`decision-word ${decision?.status !== 'READY' ? 'amber' : ''}`}>{decision?.action || 'WAIT'}</div><p>{decision?.reasons[0] || 'Record synthetic evidence, then run a cycle to see the first decision.'}</p><div className="decision-amount"><span className="number">{money(last?.outcome.amountUnits || '0')}</span><span className="label">USDC moved</span></div><div className="mini-flow sequence"><span className="stage active">EVIDENCE</span><span className="arrow">→</span><span className="stage active">RULES</span><span className="arrow">→</span><span className="stage active">OUTCOME</span></div></div><footer className="panel-foot"><button className="btn" data-action="inspect-latest" onClick={inspectLatest}>{last ? 'Inspect decision' : 'Open decision desk'} <span aria-hidden="true">↗</span></button></footer></section></div>
    <div className="lower-grid"><section className="panel"><header className="panel-head"><div><p className="eyebrow">03 / Capital boundaries</p><h2>Every USDC has a place.</h2></div><span className="label">USDC</span></header><div className="panel-body"><div className="allocation-bar" role="img" aria-label={BALANCES.map(([key, name]) => `${name}: ${money(balances[key])} USDC`).join('; ')}>{BALANCES.map(([key, name, , color]) => <span key={key} style={{ flex: balances[key], background: color }} title={name} />)}</div><div className="ledger">{BALANCES.map(([key, name, detail, color]) => <div className="ledger-row" key={key}><div className="ledger-label"><i className="swatch" style={{ background: color }} /><div className="ledger-name">{name}<small>{detail}</small></div></div><Figure className="ledger-value" name={`balance-${key}`}>{money(balances[key])}</Figure><span className="ledger-percent">{ratio(balances[key], balances.totalUnits).toFixed(0)}%</span></div>)}</div></div></section>
      <section className="panel"><header className="panel-head"><div><p className="eyebrow">04 / Evidence &amp; rules</p><h2>What the agent can see.</h2></div></header><div className="panel-body"><div className="od-row" style={{ justifyContent: 'space-between' }}><span className="small muted">{own ? 'Evidence now' : 'Evidence at snapshot'}</span><span id="evidence-usability"><Badge kind={evidence.kind}>{evidence.label}</Badge></span></div><div className="mini-facts"><div className="od-stat"><span className="label">Pool liquidity</span><span className="number" style={capStyle(observation?.availableLiquidityUnits ? money(observation.availableLiquidityUnits) : '')}>{observation?.availableLiquidityUnits ? money(observation.availableLiquidityUnits) : 'N/A'}</span><span className="small muted">Synthetic USDC</span></div><div className="od-stat"><span className="label">Supply floor</span><span className="number" style={capStyle(money(state.mandate.minLiquidityUnits))}>{money(state.mandate.minLiquidityUnits)}</span><span className="small muted">USDC required</span></div></div><div className="od-row" style={{ justifyContent: 'space-between' }}><span className="small muted">Latest recorded checks</span><span className="small mono">{pass}/{evaluated} passed</span></div><div className="rule-meter"><span style={{ transform: `scaleX(${evaluated ? pass / evaluated : 0})` }} /></div><p className="small muted">{decision ? `${decision.checks.filter(check => check.status === 'SKIPPED').length} later checks skipped by the rule path.` : 'Run a cycle to record its checks.'}</p><div className="disclosure"><p className="small muted" style={{ padding: '12px 0' }}>{own ? 'Evidence age' : 'Snapshot time'}: <span className="mono" id="evidence-age">{own ? evidenceAge(state, at) : `${when(state.at)} UTC`}</span></p><button className="btn subtle" data-route-button="knowledge" onClick={() => navigate('knowledge')}>Explore connected evidence ↗</button></div></div></section></div>
    <section className="panel section-gap"><header className="panel-head"><div><p className="eyebrow">Activity</p><h2>The latest entries.</h2></div><button className="btn subtle" data-action="open-history" onClick={openHistory}>All {run.events.length} events ↗</button></header><div className="panel-body">{view.entries.length ? <div className="activity-list">{view.entries.slice(-4).reverse().map(entry => <div className="activity-row" key={entry.eventId}><span className="activity-id">{String(view.entries.indexOf(entry) + 1).padStart(2, '0')}</span><div><h3>{eventName(entry)}</h3><p>{when(entry.at)} UTC · {entry.type === 'observe' ? 'Synthetic observation' : entry.outcome.status.toLowerCase().replaceAll('_', ' ')}</p></div><button className="btn" data-open-event={entry.eventId} aria-label={`Inspect ${eventName(entry)} at ${when(entry.at)}`} onClick={() => openEvent(entry.eventId)}>Inspect ↗</button></div>)}</div> : <div className="empty"><h3>No events yet.</h3><p>Record a synthetic observation in the decision desk, then run a cycle.</p><button className="btn" data-route-button="decisions" onClick={() => navigate('decisions')}>Open decision desk</button></div>}</div></section></>;
}
